services:
  nextjs:
    container_name: next-indevtech
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./.env.production:/app/.env.production:ro
    networks:
      - web

networks:
  web:
    external: true
