services:
  nextjs:
    container_name: next-indevtech
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./.env.production:/app/.env.production:ro
